package dev.FredyRedaTeam.PartyMasterBackend.model.Games.loup;

public enum GameState {
    DISTRIBUTION_ROLE,
    CUPIDON_CHOIX,
    AMOUREUX_REVELATION,
    GUARDIEN_CHOIX,
    VOYANTE_CHOIX,
    VOYANTE_REVELATION,
    LOUPGAROUX_CHOIX,
    SORCIERE_CHOIX,
    VILLAGE_ELECTION,
    VILLAGE_EXECUTION,
    CHASSEUR_CHOIX,
    RESULTAT
}
